apiVersion: v1
kind: Service
metadata:
  name: cust-phone-book-pc
  namespace: default
  annotations:
    lb.cke.tg.unicom/target-vports: 9002-9002
spec:
  selector:
    app: cust-phone-book-pc
  ports:
    - port: 9002
      targetPort: 9002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cust-phone-book-pc
  namespace: default
  labels:
    app: cust-phone-book-pc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cust-phone-book-pc
  template:
    metadata:
      labels:
        app: cust-phone-book-pc
    spec:
      containers:
        - name: cust-phone-book-pc
          image: harbor.dcos.wuxi.unicom.local/tj-sale-center-prod/cust-phone-book-pc
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9002
